require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Style/Documentation:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 20